# Generated by Django 5.0.6 on 2024-05-16 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="member",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name="server",
            name="description",
        ),
        migrations.AddField(
            model_name="server",
            name="description",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
